
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    
    strategy:
      matrix:
        include:
          - architecture: amd64
            runner: ubuntu-latest
          - architecture: arm64
            runner: ubuntu-22.04-arm # Or ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/${{ matrix.architecture }}
          push: true
          tags: your-repo/your-image:latest-${{ matrix.architecture }}

  create-manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Container Registry
        # ... (login steps)
      - name: Create multi-arch manifest
        run: |
          docker buildx imagetools create \
            your-repo/your-image:latest \
            your-repo/your-image:latest-amd64 \
            your-repo/your-image:latest-arm64