name: Docker Images CI

on: [push]
# on: 
#   push:
#     branches:
#       - preview
#     tags:
#       - 'v*'

jobs:

  build-images:

    name: Build '${{ matrix.architecture }}' image

    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture:
          - linux/amd64
          - linux/arm64/v8

        include:
          - architecture: linux/amd64
            dockerfile: Dockerfile
          # - architecture: arm32v7
            # dockerfile: Dockerfile.armhf
          - architecture: linux/arm64/v8
            dockerfile: Dockerfile.aarch64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Login to Docker Hub registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
            docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and publish image
        uses: ./.github/actions/docker-build-image
        with:
          dockerfile: ${{ matrix.dockerfile }}
          architecture: ${{ matrix.architecture }}

  publish-manifest:

    name: Publish multiarch manifest
    needs:
      - build-images

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Login to Docker Hub registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
            docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Create and publish manifest list
        uses: ./.github/actions/docker-create-manifest
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        with:
          multiarch: '["amd64", "arm32v7", "arm64v8"]'
