
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    
    strategy:
      matrix:
        include:
          - architecture: amd64
            runner: ubuntu-latest
          - architecture: arm64
            runner: ubuntu-22.04-arm # Or ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/${{ matrix.architecture }}
          # push: true
          # tags: richie256/rtl-schedule:latest-${{ matrix.architecture }}

      - name: Push the Docker image
        uses: docker/build-push-action@v4
        with:
          file: ${{ matrix.file }}
          push: true
          load: false
          tags: richie256/rtl-schedule:latest-${{ matrix.architecture }}
          # tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          platforms: ${{ matrix.platform }}

  create-manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
            docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      # - name: Build and publish image
      #   uses: ./.github/actions/docker-build-image
      #   with:
      #     dockerfile: ${{ matrix.dockerfile }}
      #     architecture: ${{ matrix.architecture }}
      - name: Create multi-arch manifest
        run: |
          docker buildx imagetools create \
            richie256/rtl-schedule:latest \
            richie256/rtl-schedule:latest-amd64 \
            richie256/rtl-schedule:latest-arm64